Imerg historical
OCHA-DAP/ds-pak-flooding-contingency pull request #1
Opened 2024-07-04 14:45 UTC by zackarno

2024-07-08 17:11 UTC, zackarno commented
Just sent you @caldwellst a test email via GHA. I'd like to make the caption text bigger, but I don't like that already awkwardly large line break in the text. lmk if you know a trick on that!

2024-07-09 10:06 UTC, caldwellst requested changes
Overall, the outputs look really good! However, found it very hard to navigate and understand what I should be looking at. There are `data-raw`, `R`, `src`, and `exploration` folders. A high level README explaining what is done where would go a long way to clean this up, because I struggled as `targets::tar_make()` failed due to errors with `{box}` and the GitHub actions seem to only have one workflow that is working, which is where I thought I could follow along to see what direction to run things. So yeah, documentation would help me better understand what to run and when. It also helps because it seems there are some scripts that aren't used or monitored yet?

As well, be interested to know, just for fun, why the certain basin was selected. The exploratory doc on Rpubs didn't seem to show much difference from viewing, so just documenting that in here could be interesting.

Overall though, interesting work, and excited to see what you're doing with duckdb and getting to work on cumulus!

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/R-CMD-check.yaml
> +      - uses: r-lib/actions/check-r-package@v2
Since this isn't a package, is this workflow going to work?

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/pak-email.yaml
> +          key: R-dependency-cache-${{ hashFiles('.github/depends_email.R') }}
Very cool

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/pak-email.yaml
> +  #   - cron: '10 8-23/3 * * *' # start at 8:10 AM run every 3 hours until midnight
Do you want these turned off?

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/pak-monitor.yaml
> +          name: "sa_auth.json"
Are you using GCP?

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/pak-monitor.yaml
> +          key: R-dependency-cache-${{ hashFiles('.github/depends.R') }}
This file doesn't exist.

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/pak-monitor.yaml
> +          Rscript .github/depends.R
Doesn't exist.

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/pak-monitor.yaml
> +          key: R-dependency-cache-${{ hashFiles('.github/depends_additional.R') }}
Also doesn't exist, you have `depends_email.R` and `depends_readme.R`.

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/pak-monitor.yaml
> +          Rscript .github/depends_additional.R
Just flagging one final time.

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/pak-monitor.yaml
> +          source(file.path("src", "monitor_cds_forecast.R"))
This file doesn't exist

2024-07-09 10:06 UTC, caldwellst commented on .github/workflows/update-readme.yaml
> +          Rscript -e "rmarkdown::render('README.Rmd', output_file = 'README.md')"
This file doesn't exist

2024-07-09 10:06 UTC, caldwellst commented on _targets.R
> +    "sf",
This doesn't seem to be a sufficient list? I at least had to install the `{geoarrow}` package.

2024-07-09 10:06 UTC, caldwellst commented on R/tar_load_basins.R
> +box::use(../R/utils[...])
This fails when running `tar_source()` at the start of `_targets.R`.

2024-07-09 10:06 UTC, caldwellst commented on R/tar_load_basins.R
> +box::use(../R/utils[...])
I had to switch to pathing from the base dir `box::use(R/utils[...])`

2024-07-09 10:06 UTC, caldwellst commented on _targets.R
> +      filter(
`{dplyr}` not loaded in this script.

2024-07-09 10:06 UTC, caldwellst commented on R/tar_load_basins.R
> +box::use(../R/utils[...])
And running `tar_make()` I just get complete errors whichever way I try to source it.

2024-07-09 10:06 UTC, caldwellst commented on R/tar_thresholds.R
> +      `2d` = zoo::rollsum(x = `1d`, k=2, fill = NA, align = "right"),
You can just use `rollsumr` instead of specifying `align = "right"`.

2024-07-09 10:06 UTC, caldwellst commented on R/tar_thresholds.R
> +    group_by(aoi,yr_date,name) |>
I'm assuming `name` is the same as `aoi`?

2024-07-09 10:06 UTC, caldwellst commented on R/tar_thresholds.R
> +      q_val = quantile(.data[[x]], probs = 1-(1 / rp))
Nice

2024-07-09 10:06 UTC, caldwellst commented on data-raw/02_subset_basins.R
> +box::use(arrow[...])
You use `box::use()` here, but `library()` and `source()` above, probably good to select one tool.

2024-07-09 10:06 UTC, caldwellst commented on data-raw/01_upload_hydrobasins_asia.R
> +cumulus::write_az_file(gdf_basins, container = "global","vector/hybas_asia_basins.parquet")
Seems a bit strange for this file to sit next to the file it was sourced from. Long run need to think about how we are storing and managing data.

2024-07-09 10:06 UTC, caldwellst commented on data-raw/03_pak_imerg_flooding_thresholds.R
> +targets::tar_load(df_thresholds)
I don't think you should have a `data-raw` file that requires you to have made and run the targets workflow. I expected everything in this folder to be base data that is required to run the targets. Instead, it's a mix of before and after. Can you just add this step to the `_targets` workflow if you want to put things in there?

2024-07-09 10:06 UTC, caldwellst commented on src/monitor_imerg.R
> +  scale_y_continuous(limits = c(0, y_max), expand = c(0, 0)) +
You can do this instead:

```
scale_y_continuous(limits = c(0, NA), expand = expansion(add = c(0, 10)))
```

No need to calculate `y_max` to add 10 to the max value. It will be ever so slightly different since your text annotation has a y axis value slightly above the threshold.

2024-07-09 13:20 UTC, zackarno commented on .github/workflows/R-CMD-check.yaml
> +      - uses: r-lib/actions/check-r-package@v2
hmm i think this was auto-created when I ran usethis::use_github_actions(). I can delete though

2024-07-09 13:21 UTC, zackarno commented on .github/workflows/pak-monitor.yaml
> +          name: "sa_auth.json"
nope. This was a scrap template from another repo that wasn't being used. But good call - i should delete it

[ba7f63f](https://github.com/OCHA-DAP/ds-pak-flooding-contingency/pull/1/commits/ba7f63fdc80f8fd0a76034afaf5ddccb763e5b8f)

2024-07-09 13:21 UTC, zackarno commented on .github/workflows/pak-monitor.yaml
> +          key: R-dependency-cache-${{ hashFiles('.github/depends.R') }}
deleted the yaml [ba7f63f](https://github.com/OCHA-DAP/ds-pak-flooding-contingency/pull/1/commits/ba7f63fdc80f8fd0a76034afaf5ddccb763e5b8f)

2024-07-09 13:22 UTC, zackarno commented on data-raw/02_subset_basins.R
> +box::use(arrow[...])
ha yes, i wonder if this double tooling is what is causing the issues w/ you running the `tar_make()`.

2024-07-09 13:23 UTC, zackarno commented on data-raw/01_upload_hydrobasins_asia.R
> +cumulus::write_az_file(gdf_basins, container = "global","vector/hybas_asia_basins.parquet")
yes fair point. I guess it's technically a "processed" file.  Maybe should create those distinctions again

2024-07-09 13:37 UTC, zackarno commented on data-raw/03_pak_imerg_flooding_thresholds.R
> +targets::tar_load(df_thresholds)
you have a good point! i'll write a parquet to the blob in the _targets

2024-07-09 13:39 UTC, zackarno commented on src/monitor_imerg.R
> +  scale_y_continuous(limits = c(0, y_max), expand = c(0, 0)) +
nice thats cool! I always forget all the proper args from limits/expand/expand_limits so will try the above.

I've noticed in the past that `gghdx::scale_y_continuous_hdx` almost always cuts off the top points on the top of the plot. Maybe we could use something like the above to just add a little bit of buffer on the top of the y so it works more often with less fiddling.

2024-07-09 14:35 UTC, caldwellst commented on src/monitor_imerg.R
> +  scale_y_continuous(limits = c(0, y_max), expand = c(0, 0)) +
Yes! Reflect in an issue on gghdx so we don't forget, but I think a good idea to add a bit of a buffer. The default in `ggplot2` I think is like 5% and my approach in gghdx is probably cutting that back to 0!

2024-07-09 14:43 UTC, zackarno commented on .github/workflows/R-CMD-check.yaml
> +      - uses: r-lib/actions/check-r-package@v2
[d6c4212](https://github.com/OCHA-DAP/ds-pak-flooding-contingency/pull/1/commits/d6c42125ece3271b0fa02ba531ec40780b1e930d)

2024-07-09 14:45 UTC, zackarno commented on data-raw/02_subset_basins.R
> +box::use(arrow[...])
ok i fixed this. Now functions directly used by `_targets.R` are the only one that use `library()`+ `source()` . Everything else (monitoring & data-raw) uses box.

2024-07-09 14:51 UTC, zackarno commented
> Overall, the outputs look really good! However, found it very hard to navigate and understand what I should be looking at. There are `data-raw`, `R`, `src`, and `exploration` folders. A high level README explaining what is done where would go a long way to clean this up, because I struggled as `targets::tar_make()` failed due to errors with `{box}` and the GitHub actions seem to only have one workflow that is working, which is where I thought I could follow along to see what direction to run things. So yeah, documentation would help me better understand what to run and when. It also helps because it seems there are some scripts that aren't used or monitored yet?


Thanks alot for the feedback!! very useful. This all makes alot of sense - I think I have implemented it all and the repo should be a bit clearer more & `tar_make()` should work now. Can you run `tar_make()` on your machine (added instructions for doing w/ `caffeinate` at top of _targets.R)?

> As well, be interested to know, just for fun, why the certain basin was selected. The exploratory doc on Rpubs didn't seem to show much difference from viewing, so just documenting that in here could be interesting.

Yeah it wasn't a very quantitative decision but rather to try to focus a bit more around the AOI

> Overall though, interesting work, and excited to see what you're doing with duckdb and getting to work on cumulus!

yea the early work on cumulus might need to be a bit restructured as now w/ a bit more use of the blob I feel like im finding more efficient flows. `duckdb` is really cool!

2024-07-10 00:30 UTC, zackarno commented on src/monitor_imerg.R
> +  scale_y_continuous(limits = c(0, y_max), expand = c(0, 0)) +
woops forgot to add this - implemented now: [75a7525](https://github.com/OCHA-DAP/ds-pak-flooding-contingency/pull/1/commits/75a7525972f042a75e31250f149d8500448ae3ea)

2024-07-10 13:04 UTC, caldwellst commented
Boom! Ran successfully in 1.358 hours.

2024-07-10 14:02 UTC, caldwellst approved these changes

2024-07-10 14:11 UTC, merged